      - name: Install dependencies for action
        run: |
          cd /home/runner/work/_actions/mohammedhamza1/pr-review-ollama-ai/master
          npm install parse-diff minimatch glob

      - uses: mohammedhamza1/pr-review-ollama-ai@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file-pattern: "**/*.{ts,tsx}" # Adjust based on your needs
          base-branch: "origin/${{ github.event.pull_request.base.ref }}"