name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies for action
        run: |
          cd /home/runner/work/_actions/carofi-auto/pr-review-ollama-ai/v2
          npm install parse-diff minimatch glob

      - uses: carofi-auto/pr-review-ollama-ai@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file-pattern: "**/*.{js}" # Adjust based on your needs
          base-branch: ${{ github.base_ref }} # Use the PR's base branch
