name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git branch -a

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies for action
        run: |
          cd /home/runner/work/_actions/mohammedhamza1/pr-review-ollama-ai/v2
          npm install parse-diff minimatch glob

      - uses: mohammedhamza1/pr-review-ollama-ai@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file-pattern: "**/*.{ts,tsx}" # Adjust based on your needs
          base-branch: "origin/${{ github.event.pull_request.base.ref }}"